// Generated by tools/generate_runtime_protocol.py; do not edit.
// Codex 0.154.0. Opaque union payloads are validated by runtime domain code.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitializeParams {
    pub capabilities: Option<serde_json::Value>,
    pub client_info: serde_json::Value,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadStartParams {
    pub allow_provider_model_fallback: Option<bool>,
    pub approval_policy: Option<serde_json::Value>,
    pub approvals_reviewer: Option<serde_json::Value>,
    pub base_instructions: Option<String>,
    pub config: Option<serde_json::Value>,
    pub cwd: Option<String>,
    pub developer_instructions: Option<String>,
    pub dynamic_tools: Option<Vec<serde_json::Value>>,
    pub environments: Option<Vec<serde_json::Value>>,
    pub ephemeral: Option<bool>,
    pub experimental_raw_events: Option<bool>,
    pub history_mode: Option<serde_json::Value>,
    pub mock_experimental_field: Option<String>,
    pub model: Option<String>,
    pub model_provider: Option<String>,
    pub multi_agent_mode: Option<serde_json::Value>,
    pub permissions: Option<String>,
    pub personality: Option<serde_json::Value>,
    pub project_id: Option<String>,
    pub runtime_workspace_roots: Option<Vec<serde_json::Value>>,
    pub sandbox: Option<serde_json::Value>,
    pub selected_capability_roots: Option<Vec<serde_json::Value>>,
    pub service_name: Option<String>,
    pub service_tier: Option<String>,
    pub session_start_source: Option<serde_json::Value>,
    pub thread_source: Option<serde_json::Value>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStartParams {
    pub additional_context: Option<serde_json::Value>,
    pub approval_policy: Option<serde_json::Value>,
    pub approvals_reviewer: Option<serde_json::Value>,
    pub client_user_message_id: Option<String>,
    pub collaboration_mode: Option<serde_json::Value>,
    pub cwd: Option<String>,
    pub cyber_access_program: Option<serde_json::Value>,
    pub effort: Option<serde_json::Value>,
    pub environments: Option<Vec<serde_json::Value>>,
    pub input: Vec<serde_json::Value>,
    pub model: Option<String>,
    pub multi_agent_mode: Option<serde_json::Value>,
    pub output_schema: Option<serde_json::Value>,
    pub permissions: Option<String>,
    pub personality: Option<serde_json::Value>,
    pub responsesapi_client_metadata: Option<serde_json::Value>,
    pub runtime_workspace_roots: Option<Vec<serde_json::Value>>,
    pub sandbox_policy: Option<serde_json::Value>,
    pub service_tier: Option<String>,
    pub service_tier_for_turn: Option<String>,
    pub summary: Option<serde_json::Value>,
    pub thread_id: String,
    pub tool_output: Option<serde_json::Value>,
    pub turn_trigger: Option<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnInterruptParams {
    pub thread_id: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DynamicToolCallParams {
    pub arguments: serde_json::Value,
    pub call_id: String,
    pub namespace: Option<String>,
    pub thread_id: String,
    pub tool: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DynamicToolCallResponse {
    pub content_items: Vec<serde_json::Value>,
    pub success: bool,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputParams {
    pub auto_resolution_ms: Option<i64>,
    pub is_blocking: bool,
    pub item_id: String,
    pub questions: Vec<serde_json::Value>,
    pub thread_id: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputResponse {
    pub answers: serde_json::Value,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadTokenUsageUpdatedNotification {
    pub thread_id: String,
    pub token_usage: serde_json::Value,
    pub turn_id: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnCompletedNotification {
    pub thread_id: String,
    pub turn: serde_json::Value,
}
