//! Bounded read model for the existing operations page and aggregated inbox.
use serde_json::{Value, json};
use sqlx::{Postgres, Transaction};
pub async fn detail(
    tx: &mut Transaction<'_, Postgres>,
    requirement: i64,
) -> Result<Value, sqlx::Error> {
    let mut result:Value=sqlx::query_scalar("SELECT jsonb_build_object('classification_todo',COALESCE((g.measured->>'classification_todo')::bigint,0),'configured',g.policy_version IS NOT NULL,'policy_version',g.policy_version,'actual_bytes',(g.measured->>'actual')::bigint,'available_bytes',(g.measured->>'available')::bigint,'measured_at',g.measured_at,'control_bytes',(p.document->>'control_bytes')::bigint,'global_limit',(p.document->>'global_bytes')::bigint,'reserved_bytes',(SELECT COALESCE(SUM(outstanding),0)::bigint FROM storage_allocation),'requirement_allocated',(SELECT COALESCE(SUM(l.allocated),0)::bigint FROM storage_allocation l JOIN storage_attempt a ON a.run_id=l.run_id WHERE a.requirement_id=$1),'protected_bytes',(SELECT COALESCE(SUM(m.actual_bytes),0)::bigint FROM storage_material m JOIN storage_attempt a ON a.run_id=m.run_id WHERE a.requirement_id=$1 AND m.protection IS NOT NULL AND m.status<>'deleted' AND NOT EXISTS(SELECT 1 FROM storage_material parent WHERE parent.protection IS NOT NULL AND parent.status<>'deleted' AND starts_with(m.path,parent.path || '/'))),'cleanup_todo',((SELECT count(*) FROM storage_material m JOIN storage_attempt a ON a.run_id=m.run_id WHERE a.requirement_id=$1 AND ((m.retry->>'todo')::boolean OR m.protection IN ('partial archive; reconcile','unknown identity','unknown preparation identity','partial/pending requires reconciliation')))+(SELECT count(*) FROM runtime_evidence e JOIN storage_attempt a ON a.run_id=e.run_id WHERE a.requirement_id=$1 AND (e.cleanup_retry->>'todo')::boolean)+CASE WHEN (g.scan_retry->>'todo')::boolean THEN 1 ELSE 0 END)) FROM storage_guard g LEFT JOIN storage_policy p ON p.version=g.policy_version WHERE g.id=1")
        .bind(requirement).fetch_one(&mut **tx).await?;
    result["materials"]=json!(sqlx::query_scalar::<_,Value>("SELECT jsonb_build_object('id',m.id,'run_id',m.run_id,'kind',m.kind,'category',m.category,'status',m.status,'actual_bytes',m.actual_bytes,'expires_at',m.expires_at,'protection',m.protection,'attempts',(m.retry->>'attempts')::bigint,'next_attempt_at',m.retry->'next_attempt_at','failure',m.retry#>>'{last_failure,detail}','deleted_at',m.deleted_at,'reason',m.deletion_reason,'replacement',(SELECT replacement.id FROM storage_material replacement WHERE replacement.path=m.archive->>'path'),'resolved_by',a.resolved_by,'identity',a.identity::text,'summary',a.summary::text) FROM storage_material m JOIN storage_attempt a ON a.run_id=m.run_id WHERE a.requirement_id=$1 ORDER BY m.created_at DESC,m.id LIMIT 100")
        .bind(requirement).fetch_all(&mut **tx).await?);
    result["categories"]=json!(sqlx::query_scalar::<_,Value>("SELECT jsonb_build_object('name',c.key,'actual_bytes',(g.measured->'categories'->>c.key)::bigint,'reserved_bytes',(SELECT COALESCE(SUM(outstanding),0)::bigint FROM storage_allocation WHERE category=c.key),'limit_bytes',(c.value->>'bytes')::bigint,'retention_seconds',(c.value->>'seconds')::bigint) FROM storage_guard g JOIN storage_policy p ON p.version=g.policy_version CROSS JOIN LATERAL jsonb_each(p.document->'categories') c WHERE g.id=1 ORDER BY c.key")
        .fetch_all(&mut **tx).await?);
    Ok(result)
}
