#!/usr/bin/env python3
"""Generate the consumed app-server wire records from the locked binary schema.

Union/extension payloads remain JSON values and are validated at the domain
boundary. No generated code executes user input. --check detects schema drift.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
NAMES = ["InitializeParams", "ThreadStartParams", "TurnStartParams",
         "TurnInterruptParams", "DynamicToolCallParams", "DynamicToolCallResponse",
         "ToolRequestUserInputParams", "ToolRequestUserInputResponse",
         "ThreadTokenUsageUpdatedNotification", "TurnCompletedNotification"]


def rust_type(schema):
    if not isinstance(schema, dict):
        return "serde_json::Value"
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((item for item in kind if item != "null"), None)
    if kind == "array":
        return "Vec<" + rust_type(schema["items"]) + ">"
    return {"string": "String", "integer": "i64", "boolean": "bool",
            "number": "f64"}.get(kind, "serde_json::Value")


def generate(directory):
    lines = ["// Generated by tools/generate_runtime_protocol.py; do not edit.",
             "// Codex 0.157.1. Opaque union payloads are validated by runtime domain code.",
             "use serde::{Deserialize, Serialize};", ""]
    hashes = {}
    for name in NAMES:
        path = sorted(directory.rglob(name + ".json"))[0]
        schema = json.loads(path.read_text())
        hashes[name] = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.extend(["#[derive(Clone, Debug, Default, Serialize, Deserialize)]",
                      "#[serde(rename_all = \"camelCase\")]", "pub struct " + name + " {"])
        for wire, prop in sorted(schema["properties"].items()):
            field = re.sub(r"(?<!^)(?=[A-Z])", "_", wire).lower()
            typ = rust_type(prop)
            if wire not in schema.get("required", []):
                typ = "Option<" + typ + ">"
            lines.append(f"    pub {field}: {typ},")
        lines.extend(["}", ""])
    return "\n".join(lines), json.dumps(hashes, indent=2, sort_keys=True) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    version = subprocess.check_output(["codex", "--version"], text=True).strip()
    if version != (ROOT / "codex-version.lock").read_text().strip():
        raise SystemExit("Codex version differs from lock")
    with tempfile.TemporaryDirectory() as temporary:
        directory = Path(temporary)
        subprocess.run(["codex", "app-server", "generate-json-schema", "--experimental",
                        "--out", str(directory)], check=True, capture_output=True)
        source, hashes = generate(directory)
        rs = directory / "protocol.rs"
        rs.write_text(source)
        subprocess.run(["rustfmt", "--edition", "2024", str(rs)], check=True)
        outputs = {ROOT / "apps/server/src/runtime_protocol.rs": rs.read_text(),
                   ROOT / "docs/runtime-schema-lock.json": hashes}
        for path, content in outputs.items():
            if args.check:
                if path.read_text() != content:
                    raise SystemExit(f"generated protocol drift: {path.name}")
            else:
                path.write_text(content)


if __name__ == "__main__":
    main()
